REM   Script: lab - 6
REM   Nested Queries on sample exercises

CREATE TABLE STUDIES_010 (PNAME varchar2(20),SPLACE varchar2(20),COURSE varchar2(20),CCOST int);

desc studies_010


insert into STUDIES_010 values ('BALAJI','CHENNAI','CSE',200000) ;

insert into STUDIES_010 values ('SUBRAHMANYAM','HYDERABAD','ECE',250000) ;

select * from studies_010 ;

CREATE TABLE SOFTWARE (PNAME varchar2(20),TITLE varchar2(20),DEVIN varchar2(20),SCOST int,DCOST int,SOLD int);

insert into  SOFTWARE values('BALAJI','PROGRAM','PYTHON',2000,3000,7000);

insert into SOFTWARE values('SUBRAHMANYAM','WEB','C',2000,4000,6500);

select * from software;

delete from software where SOLD = 6500;

insert into SOFTWARE values('SUBRAHMANYAM','WEB','C',1000,4000,6500);

insert into SOFTWARE values('SUBHASH','AI','JAVA',3000,2000,6000);

select * from SOFTWARE;

create table PROGRAMMER (PNAME varchar2(20),DOB date,DOJ date,SEX char,PROF1 varchar2(20),PROF2 varchar2(20),SAL int);

insert into PROGRAMMER values('BALAJI',TO_DATE('17/12/2001', 'DD/MM/YYYY'),TO_DATE('12/03/2020', 'DD/MM/YYYY'),'M','PYTHON','C',20000);

insert into PROGRAMMER values('SUBRAHMANYAM',TO_DATE('16/12/2001', 'DD/MM/YYYY'),TO_DATE('15/11/2020', 'DD/MM/YYYY'),'M','PYTHON','JAVA',40000);

insert into PROGRAMMER values('SUBHASH',TO_DATE('15/12/2001', 'DD/MM/YYYY'),TO_DATE('30/07/2020', 'DD/MM/YYYY'),'M','JAV','C',50000);

select * from PROGRAMMER;

SELECT AVG(SCOST) FROM SOFTWARE WHERE DEVIN = 'PYTHON';

SELECT PNAME,TRUNC(MONTHS_BETWEEN(SYSDATE,DOB)/12)"AGE",TRUNC(MONTHS_BETWEEN(SYSDATE,DOJ)/12)"EXPERIENCE" FROM PROGRAMMER;

SELECT PNAME FROM STUDIES_010 WHERE COURSE = 'EEE';

SELECT MAX(SOLD) FROM SOFTWARE;

SELECT MIN(CCOST) FROM STUDIES_010;

SELECT COUNT(*) FROM STUDIES_010 WHERE COURSE = 'ECE';

SELECT SUM(SCOST*SOLD-DCOST) FROM SOFTWARE GROUP BY DEVIN HAVING DEVIN = 'C';

SELECT * FROM SOFTWARE WHERE PNAME = 'SUBRAHMANYAM';

SELECT * FROM STUDIES_010 WHERE SPLACE = 'HYDERABAD';

SELECT * FROM SOFTWARE WHERE SCOST*SOLD-DCOST>5000;

SELECT CEIL(DCOST/SCOST) FROM SOFTWARE;

SELECT * FROM SOFTWARE WHERE SCOST*SOLD>= DCOST;

SELECT MAX(SCOST) FROM SOFTWARE GROUP BY DEVIN HAVING DEVIN = 'C';

SELECT COUNT(*) FROM SOFTWARE WHERE DEVIN = 'JAVA';

SELECT COUNT(*) FROM STUDIES_010 WHERE SPLACE = 'DELHI';

SELECT COUNT(*) FROM STUDIES_010 WHERE SPLACE = 'HYDERABAD';

SELECT COUNT(*) FROM STUDIES_010 WHERE CCOST BETWEEN 2500 AND 5000;

SELECT COUNT(*) FROM STUDIES_010 WHERE CCOST BETWEEN 2500 AND 6000;

SELECT COUNT(*) FROM STUDIES_010 WHERE CCOST BETWEEN 1500 AND 6000;

SELECT AVG(CCOST) FROM STUDIES_010;

SELECT * FROM PROGRAMMER WHERE PROF1 = 'PYTHON' OR PROF2 = 'C';

SELECT * FROM PROGRAMMER WHERE PROF1 = 'PYTHON' OR PROF2 = 'C';

SELECT * FROM PROGRAMMER WHERE PROF1 = 'PYTHON' OR PROF2 = 'C';

SELECT * FROM PROGRAMMER WHERE PROF1 IN ('C','PASCAL') OR PROF2 IN ('C','PASCAL');

SELECT * FROM PROGRAMMER WHERE PROF1 NOT IN ('PYTHON','JAVA') AND PROF2 NOT IN ('PYTHON','JAVA');

SELECT TRUNC(MAX(MONTHS_BETWEEN(SYSDATE,DOB)/12)) FROM PROGRAMMER WHERE SEX = 'M';

SELECT PNAME,TRUNC(MONTHS_BETWEEN(SYSDATE,DOJ)/12) FROM PROGRAMMER ORDER BY PNAME DESC;

SELECT PNAME FROM PROGRAMMER WHERE TO_CHAR(DOB,'MON') = TO_CHAR(SYSDATE,'MON');

SELECT COUNT(*) FROM PROGRAMMER WHERE SEX = 'F';

SELECT COUNT(*) FROM PROGRAMMER WHERE SEX = 'M';

SELECT DISTINCT(PROF1) FROM PROGRAMMER WHERE SEX = 'M';

SELECT AVG(SAL) FROM PROGRAMMER;

SELECT COUNT(*) FROM PROGRAMMER WHERE SAL BETWEEN 1000 AND 5000;

SELECT PNAME,TITLE,SCOST FROM SOFTWARE WHERE SCOST IN(SELECT MAX(SCOST) FROM SOFTWARE GROUP BY PNAME);

SELECT * FROM PROGRAMMER WHERE PROF1 NOT IN ('C','JAVA','PASCAL') AND PROF2 NOT IN ('C','JAVA','PASCAL') 
;

